<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Qxf2                Services_stripe__2e55a3</name>
   <tag></tag>
   <elementGuidId>737cfd76-83f3-4331-8cc4-1f3ba1889cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='stripe_checkout_app']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;stripe_checkout_app&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5b5144c8-0249-4e97-882a-a59182facb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d993d87-7667-449c-b0c5-2a9aa58fd6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=9cd2969a-8a43-49e2-b590-973163b842ba</value>
      <webElementGuid>aa2e9777-d446-4ae5-9e0e-b319a8354a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>6e72a855-5831-442f-b99d-5f237c34a94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>ea148406-752f-4e8f-b860-fcb6da641cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9bbe5460-8d7c-410d-a246-5ee25ab83b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iframe[@class=&quot;stripe_checkout_app&quot;]</value>
      <webElementGuid>8a239e57-b343-4243-aefe-d864af6b265f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='stripe_checkout_app']</value>
      <webElementGuid>8dfab792-3c17-43c8-a7ec-c4ae9f57a46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9d683136-4b56-4eeb-ac2a-2b8f3457aac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=9cd2969a-8a43-49e2-b590-973163b842ba' and @name = 'stripe_checkout_app']</value>
      <webElementGuid>41fd8038-3d6f-454e-8577-d1165a32dd29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
