<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Temperature</name>
   <tag></tag>
   <elementGuidId>e31bc5a4-933a-484f-9e8d-1f8bcfe3d98e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='temperature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#temperature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6fce3cc-4bed-4b77-a6b5-a7efe9d48dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>temperature</value>
      <webElementGuid>8996ab49-1173-4277-9900-7c11e36b4a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>47 °C</value>
      <webElementGuid>2336f25b-5f05-4817-9dfa-3abe8ad79d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperature&quot;)</value>
      <webElementGuid>f431e598-50ef-4c69-8fda-175b50bae26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='temperature']</value>
      <webElementGuid>58de9833-1ad7-4919-8900-fdd7b95f51ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weather']/span</value>
      <webElementGuid>56952b7b-45f0-4a95-89d6-37e6ad09bbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current temperature'])[1]/following::span[2]</value>
      <webElementGuid>3b46bba0-a787-4d73-8513-7acacff8dcd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moisturizers'])[1]/preceding::span[1]</value>
      <webElementGuid>f7563a58-06e9-432e-855f-32301d7d22ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='47']/parent::*</value>
      <webElementGuid>90c095dd-39b1-46c6-b9fb-e946f49e67a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/span</value>
      <webElementGuid>c2ce70b6-b16c-4af7-a805-bc0311d3810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'temperature' and (text() = '47 °C' or . = '47 °C')]</value>
      <webElementGuid>62400ff6-549c-44fb-b50a-d135d7cf783d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
